window:
  padding:
    x: 6
    y: 0
font:
  size: 13
  normal:
    family: Monaco
    style: Regular
colors:
  primary:
    foreground: "#D4D8DF"
    background: "#212C42"
  normal:
    black: "#212C42"
    red: "#A3EA2A"
    green: "#A3EA2A"
    yellow: "#ECBB0A"
    blue: "#7979FF"
    magenta: "#ECBB0A"
    cyan: "#79BEFF"
    white: "#D4D8DF"
  bright:
    black: "#212C42"
    red: "#A3EA2A"
    green: "#A3EA2A"
    yellow: "#ECBB0A"
    blue: "#7979FF"
    magenta: "#ECBB0A"
    cyan: "#79BEFF"
    white: "#D4D8DF"