# Alacritty Configuration

# Window settings
[window.padding]
x = 6
y = 6

# Font settings
[font]
size = 12.7

[font.normal]
family = "Fira Code Retina"
style = "Regular"

# Primary colors for background and foreground
[colors.primary]
background = "#353c45"  # Dark gray background
foreground = "#d8dee9"  # Light gray foreground

# Cursor appearance
[colors.cursor]
cursor = "#d8dee9"  # Cursor color
text = "#ffffff"    # Text color under the cursor

# Selection colors
[colors.selection]
background = "#d8dee9"  # Highlighted background color
text = "#353c45"        # Highlighted text color

# Standard (normal) colors
[colors.normal]
black   = "#000000"
red     = "#f92672"
green   = "#a6e22e"
yellow  = "#f4bf75"
blue    = "#3d90e3"
magenta = "#ae81ff"
cyan    = "#3d90e3"
white   = "#f8f8f2"

# Bright (bold) colors
[colors.bright]
black   = "#555555"
red     = "#f92672"
green   = "#a6e22e"
yellow  = "#ffd866"
blue    = "#3d90e3"
magenta = "#6679cc"
cyan    = "#9afbff"
white   = "#ffffff"
